data_dir: "/home/aryal007/DynamicEarthNet/Track2/data/"
run_name: 'runs_A'
model_opts:
  args: 
    inchannels: 11
    outchannels: 2
    net_depth: 7
    dropout: 0.3
    spatial: True
    first_channel_output: 8
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
reg_opts:
  l1_reg: 0.0005