data_dir: "/home/aryal007/DynamicEarthNet/Track2/data/"
class_name: "Floodwater"
batch_size: 2
run_name: "C"
epochs: 251
save_every: 25
use_channels: [0,1,2,3,4,5,10,11,12]
loss_opts:
  name: "dice"
  masked: True
  weights: [0.01, 0.99]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 9
    outchannels: 2
    net_depth: 6
    dropout: 0.2
    spatial: True
    first_channel_output: 48
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
log_opts:
  mask_names: ["XBackground", "Floodwater"]
metrics_opts: ["IoU", "precision", "recall"]
grad_accumulation_steps: 8
reg_opts:
  l1_reg: 0.00001