data_dir: "/home/aryal007/DynamicEarthNet/Track2/data/"
class_name: "Floodwater"
batch_size: 1
run_name: "final_A_minmax"
epochs: 51
save_every: 50
use_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12]
loss_opts:
  name: "dice"
  masked: True
  weights: [0.01, 0.99]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 13
    outchannels: 2
    net_depth: 7
    dropout: 0.2
    spatial: True
    first_channel_output: 16
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
log_opts:
  mask_names: ["XBackground", "Floodwater"]
metrics_opts: ["IoU", "precision", "recall"]
grad_accumulation_steps: None
fine_tune: True
reg_opts:
  l1_reg: 0.00001